### ISSUE TITLE
npm installs serialport 5.x because ">=" in package.json

### ISSUE THREAD

**Issue by Nickforall** [normen/homebridge-433-arduino#3]
therefore it doesn't work, since the readline function changed in serialport 5.0

```
/usr/local/lib/node_modules/homebridge-433-arduino/index.js:19
            parser: SerialPort.parsers.readline("\n")
                                       ^

TypeError: SerialPort.parsers.readline is not a function
    at new ArduinoSwitchPlatform (/usr/local/lib/node_modules/homebridge-433-arduino/index.js:19:40)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by normen** [comment]
Aight, gotta change that for the next release, thanks!
